fansubs/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView
from django.conf.urls.static import static 
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from subbers.views import index, index_offline
from airing.views import status, iframe, detail
import haystack
from tastypie.api import Api
from .api import EntryResource, SerieResource, WordpressResource
api = Api(api_name="v1")

api.register(EntryResource())
api.register(SerieResource())
api.register(WordpressResource())

urlpatterns = [
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^showtimes/$', status, name='status'),
    url(r'^api/', include(EntryResource().urls)),
    url(r'^api/', include(api.urls)),
    url(r'^iframe/$', iframe, name='iframe'),
#    url(r'^$', index, name='home'),
    url(r'^$', RedirectView.as_view(url='/showtimes/'), name='home'),
    url(r'^showtimes/(?P<pk>\d+)/$', detail, name='detail'),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + staticfiles_urlpatterns()

airing/models.py
from django.db import models
from subbers.models import Fansub

class Serie(models.Model):
    name = models.CharField(max_length=1000)
    slug = models.SlugField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return "%s " % (self.name)


class Wordpress(models.Model):
    slug = models.SlugField()
    title = models.CharField(max_length=100)
    body = models.TextField()
    categorias = models.CharField(max_length=100)
    tags = models.CharField(max_length=100)
    serie = models.OneToOneField("Serie")

    def __unicode__(self):
        return u"%s" % self.title



class Work(models.Model):
    anime = models.ForeignKey(Serie)
    fansub = models.ForeignKey(Fansub)
    url = models.URLField(blank=True, null=True)
    chapters_completed = models.IntegerField(default=0, verbose_name="Episodios en proceso" )
    chapters_total = models.IntegerField(default=0)

    editor_nick = models.CharField(max_length=100, help_text="Correcion", )
    editor_finished = models.BooleanField(default=False)

    translator_nick = models.CharField(max_length=100)
    translator_finished = models.BooleanField(default=False)

    typesetter_nick = models.CharField(max_length=100,help_text="Edicion")
    typesetter_finished = models.BooleanField(default=False)

    timer_nick =  models.CharField(max_length=100)
    timer_finished = models.BooleanField(default=False)

    encoder_nick =  models.CharField(max_length=100)
    encoder_finished = models.BooleanField(default=False)

    quality_check1_nick =  models.CharField(max_length=100, )
    quality_check1_finished = models.BooleanField(default=False)
    quality_check2_nick = models.CharField(max_length=100, blank =True, null =True, )
    quality_check2_finished = models.BooleanField(default=False)


    karaokesync_nick =  models.CharField(max_length=100, blank =True, null =True, )
    karaokesync_finished = models.BooleanField(default=False)

    karaoke_nick =  models.CharField(max_length=100, blank =True, null =True, )
    karaoke_finished = models.BooleanField(default=False)
    status = models.BooleanField(default=False, editable = False)
    revision_nick = models.CharField(max_length=100, null =True, blank =True)
    revision_finished = models.BooleanField(default=False)
    greets = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True,editable = True)

    class Meta:
        ordering = ("anime__name","-modified_at",)

    def __unicode__(self):
        return "%s - %s " % (self.anime, self.pk)

    def save(self, *args, **kwargs):
        self.status = self.is_completed()
        super(Work,self).save(*args, **kwargs)

    def __finish_task(self):

        from bot_plugins.showtimes.utils import OPTS
        for i in OPTS:
            task_finish = getattr(self, "%s_finished" % i)
            if not task_finish:
                return False
        return True

    def is_completed(self):
        season = self
        if season.chapters_completed > 0  and \
           season.chapters_completed == season.chapters_total and \
           self.__finish_task():
            return True
        return False

subbers/models.py
from django.db import models
import re

class Regex(models.Model):
    regex = models.TextField()
    fansub = models.ForeignKey("Fansub")
    order = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ("-order",)



class Fansub(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField()
    nyaa_id = models.CharField(max_length=100)
    websites = models.CharField(max_length=400,blank=True, null=True)
    showtime_url = models.URLField(blank=True, null=True)
    logo = models.URLField(blank=True, null=True)
    irc = models.CharField(blank=True, null=True, max_length=100)
    announce = models.CharField(max_length=200, blank=True, null=True, help_text="ejemplo: *,#chan1,chan2")
    description_subtitles = models.TextField()
    description_subtitles_alter = models.TextField(blank=True, null=True)
    description_nyaa = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)


    def __unicode__(self):
        return u"%s" %self.name

class Entry(models.Model):
    fansub = models.ForeignKey(Fansub)
    summary = models.TextField()
    title = models.TextField()
    link  = models.URLField()
    magnet = models.TextField(null=True,blank=True)
    published_at = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.title

    class Meta:
        unique_together = ("fansub", "title" )
        ordering = ("-published_at",)

    def _parse(self):
        title = self.title.replace("_"," ").replace("HDTV","720p")
        for i in self.fansub.regex_set.all():
            regex_str = i.regex
            m = re.match(regex_str, title, re.UNICODE)
            result =None
            if m:
                result = m.groupdict()
                return result

    @property
    def data(self):
        return self._parse()
    @property
    def info(self):
        return self.link.replace("download","view")

class Access(models.Model):
    nick = models.CharField(max_length=10)
    is_admin = models.BooleanField(default=False)
    def __unicode__(self):
        return self.nick

airing/views.py
from django.views.generic import ListView, DetailView
from .models import Work as Season
from subbers.models import Fansub

class Status(ListView):
    model = Season
    template_name = "airing/iframe.html"

    def get_queryset(self):
        qs = super(Status, self).get_queryset()
        fansub = self.request.GET.get("fansub")
        if fansub:
            qs = qs.filter(fansub__slug__icontains=fansub)
        return qs

    def get_context_data(self,**kwargs):
        context = super(Status, self).get_context_data(**kwargs)
        fansub_id = self.request.GET.get("fansub")
        if fansub_id:
            fansub = Fansub.objects.get(slug=fansub_id)
            context.update({'fansub':fansub})
        return context 


status = Status.as_view()

class Iframe(Status):
    template_name = "airing/iframe.html"
iframe = Iframe.as_view()

detail = DetailView.as_view(model=Season)

subbers/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView, DetailView
from .models import Entry, Fansub


class Offline(TemplateView):
    template_name ="offline.html"

index_offline = Offline.as_view()

class IndexView(ListView):
    model = Entry

    def get_queryset(self):
        qs = super(IndexView, self).get_queryset()
        fansub_id = self.request.GET.get("fansub")
        if fansub_id:
            qs = qs.filter(fansub__slug__icontains=fansub_id)
        return qs

    def get_context_data(self,**kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        fansub_id = self.request.GET.get("fansub")
        if fansub_id:
            fansub = Fansub.objects.get(slug=fansub_id)
            context.update({'fansub':fansub})
        return context 

index = IndexView.as_view()


detail = DetailView.as_view(model=Entry)

airing/templates/airing/iframe.html
{% extends "airing/status.html"%}
{% block header %}
<script src="{{MEDIA_URL}}stack/stacktable.js"></script>
<link rel="stylesheet" type="text/css" href="{{MEDIA_URL}}stack/stacktable.css"></link-->
{% endblock %}

{% block  content %}
{% block  header_content%}{% endblock %}
<style>body {padding:0px;
font-size:10px;}

 </style>

<script>
$(document).ready(function(){
  $('table').stacktable();
});
</script>

 <div style="float:right;">
   <a href="{% url 'status' %}?fansub={{fansub.slug}}" target="_blank">Ver todo</a>
 </div>
{{block.super}}
{% endblock %}

airing/templates/airing/status.html
{% extends "base.html" %}
 {% block sidebar %}
 {% endblock %}
 {% block js %}

<script>
$(document).ready(function(){
  var menus =   $("ul#menu a");
  menus.on("click", function(e){
    e.preventDefault();
    $("ul#menu li").removeClass("active");
    $(this).parent().addClass("active");

    var id = $(this).attr("id");
    if( id =="todos") {
          $(".completed").show();
          $(".uncompleted ").show();
    } else if( id=="terminados"){
          $(".completed").show();
          $(".uncompleted").hide();     
    } else {
          $(".completed").hide();
          $(".uncompleted").show();
    }
  
});
  if( window.location.hash == ""){
      $("#enproceso").trigger("click");
  } else {
    $(window.location.hash).trigger("click");
  }
});
</script>
 {% endblock %}

{% block content %}
 {%regroup object_list|dictsort:"fansub.name" by fansub.name as season_list%}
  <div class="col-sm-12 col-xs-12 col-md-12 col-lg-12">
    {%block header_content %}
<div class="page-header">
  <h1> Showtimes </h1>
</div>
{% endblock %}

            <ul class="nav nav-tabs" role="tablist" id="menu">
                <li class="active"><a href="#todos" id="todos">Todos</a></li>
                 <li><a href="#terminados" id="terminados">Terminados</a></li>
                <li><a href="#enproceso" id="enproceso">En Proceso</a></li>
            </ul>


      {%for season in season_list %}
      <div class="panel panel-primary ">
          <div class="panel-heading">
             <h2 class="panel-title center-block">
                <a target="_blank" href="{% url 'status'%}?fansub={{season.grouper|slugify}}"> {{season.grouper}} </a>
              </h2>
          </div>

              <table class="table table-condensed table-bordered">
                
                    <thead>
                        <tr class="active">
                            <th style="width:315px;">Anime</th>
                            <th>Episodios </th>
                                <!--th>Compresión</th-->
                                <th>Traductor</th>
                                <th>Sincronizador</th>
                                <th>Corrector</th>
                                <!--th> Karaoke </th-->
                                <th>Editor</th>
                                <th>QC1</th>
                                <th style="width:95px">QC2</th>

                                    <th colspan="2">Actualizada hace</th>
                        </tr>
                    </thead>
              <tbody>
              {%for season in season.list %}
                <tr  title="{{season.fansub.slug}} {{season.anime.slug}}" {%spaceless%}
                 {%if not season.is_completed%}
                            class="uncompleted"
                  {% else %}
                            class="success completed"
                  {%endif %}
                {%endspaceless%}>
                <td>                              {% if season.url %}
                      <a target="_blank" href="{{season.url}}"> {{season.anime.name}}</a>
                      {% else %}
                        {{season.anime.name}}
                        {%endif %}
                    </td>
                    <td>
                    {%if season.is_completed %}
                            <span class="label label-success">TERMINADA</span>
                    {% else %}
                                  {{season.chapters_completed|stringformat:"02d"}}/{{season.chapters_total|stringformat:"02d"}}
                    {% endif %}
                    </td>
                                <!--td data-en="encoder" {%spaceless%}
                                      {%if not season.encoder_finished%}
                                       class="danger"
                                      {% else %} 
                                    class="success" 
                                  {%endif%}
                                  {%endspaceless%}>
                                    {{season.encoder_nick|default:""}}
                                </td-->

                                <td data-en="translator" {%spaceless%}
                                      {%if not season.translator_finished%}
                                       class="danger"
                                      {% else %} 
                                    class="success" 
                                  {%endif%}
                                  {%endspaceless%}>
                                  {{season.translator_nick|default:""|default:"nick1"}}
                                </td>

                                <td data-en="timer" {%spaceless%}
                                      {%if not season.timer_finished%}
                                     class="danger"
                                      {% else %} 
                                    class="success" 
                                  {%endif%}
                                  {%endspaceless%}>
                                    {{season.timer_nick|default:""}}
                                </td>

                             

                                <td data-en="editor" {%spaceless%}
                                      {%if not season.editor_finished%}
                                       class="danger"
                                      {% else %} 
                                    class="success" 
                                  {%endif%}
                                  {%endspaceless%}>

                                    {{season.editor_nick|default:""}}
                                </td>
                                <!-- td data-en="karaoke" {%spaceless%}
                                      {%if not season.karaoke_finished%}
                                       class="danger"
                                      {% else %} 
                                    class="success" 
                                  {%endif%}
                                  {%endspaceless%}>

                                    {{season.karaoke_nick|default:""}}
                                </td-->

                                <td data-en="typesetter" {%spaceless%}
                                      {%if not season.typesetter_finished%}
                                       class="danger"
                                      {% else %} 
                                    class="success" 
                                  {%endif%}
                                  {%endspaceless%}>

                                    {{season.typesetter_nick|default:""}}
                                </td>


                                <td {%spaceless%}
                                      {%if not season.quality_check1_finished%}
                                       class="danger"
                                      {% else %} 
                                    class="success" 
                                  {%endif%}
                                  {%endspaceless%}>

                                    {{season.quality_check1_nick|default:""}}
                                </td>

                                <td {%spaceless%}
                                      {%if not season.quality_check2_finished%}
                                       class="danger"
                                      {% else %} 
                                    class="success" 
                                  {%endif%}
                                  {%endspaceless%}>

                                    {{season.quality_check2_nick|default:""}}
                                </td>

                    <td style="width:23px;"> 

                      <a href="{% url 'detail' season.pk %}" class="center-block" title="Datos Extra"> <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span></a>
                    </td>


                  <td>
                           {{season.modified_at|timesince}}
                    </td>
                    </tr>
            {% endfor %}
                      <!-- tr>
                                <td colspan="12" class="active     "> 
 
            {%for season in season.list %}
                 {%if not season.is_completed%}
                              <small> {{season.fansub.slug|lower}} {{season.anime.slug|lower}} </small> |
                 {% endif %} 
              {% endfor %}
                              </td>
              </tr-->

              </tbody>
              </table>
        </div>
      {% endfor %}
  </div>

{% endblock %}

airing/templates/airing/work_detail.html
{% extends "base.html" %}
{% block sidebar %} {% endblock %}
{% block content  %}
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
<blockquote>
  <h2>
    <a href="{{object.url}}" target="_blank">
    {{object.anime}}
  </a>
    </h2> <small>
    {{object.fansub}}</small>

</blockquote>
  <a class="pull-right small"  href="http://hoshizora.moe/?page_id=89" target="_blank">Descripción de los puestos</A>


<p>
  Compresión: {{object.encoder_nick}}  <span class="glyphicon glyphicon-{{object.encoder_finished|yesno:"ok,remove"}}"></span>
</p>


<p>
  Karaoke (Efectos): {{object.karaoke_nick}}  <span class="glyphicon glyphicon-{{object.karaoke_finished|yesno:"ok,remove"}}"></span>
</p>

{% if object.karaokesync_nick %}
<p>
   Karaoke (Sincronización): {{object.karaokesync_nick}}  <span class="glyphicon glyphicon-{{object.karaokesync_finished|yesno:"ok,remove"}}"></span>
</p>
{% endif %}

{%if object.revision_nick %}
<p>
 Revisión [Batch]:{{object.revision_nick}}  <span class="glyphicon glyphicon-{{object.revision_finished|yesno:"ok,remove"}}"></span>

</p>
{%endif%}
{% if object.greets %}
<p>
Agradecimientos: {{object.greets|default:"..."}}
</p>
{% endif %}
</div>

<a href="/" class="btn btn-default "> Regresar </a>

{% endblock %}

subbers/templates/_sidebar.html
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar nav-pills nav-stacked">
            <li class="">
            <a href="{% url 'home' %}"><b>Torrent Index</b></a>
              </li>
            {% for i in fansubs %}
              <li>
              <a href="{% url 'home' %}?fansub={{i.slug}}">{{i.name}}  <span class="badge">{{i.entry_set.count}}</span></a>
              </li>
            {% endfor %}
          </ul>
          <p> 
          Desarrollado por <a href="https://twitter.com/waifuapp">Waifu app</a>
          </p>
       </div>

subbers/templates/base.html
{% load flatpages %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{MEDIA_URL}}/favicon.ico">

    <title>{% block title %}Showtimes{% endblock %}</title>

    <link href="{{MEDIA_URL}}/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{MEDIA_URL}}/bootstrap.min.css" rel="stylesheet">

    <link href="{{MEDIA_URL}}dashboard.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="{{MEDIA_URL}}/assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{{MEDIA_URL}}/assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

{% block header%}{% endblock%}
  </head>

  <body>
    <div class="container-fluid">
      {% block container %}

        <div class="row">
          {% block sidebar %}      
              {% include "_sidebar.html"%}
          {% endblock %}

          {% block content %}

          {% endblock %}
    
        </div>
      {% endblock %}
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{MEDIA_URL}}/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{{MEDIA_URL}}/assets/js/ie10-viewport-bug-workaround.js"></script>

    {%block js %}
    {% endblock %}
  </body>
</html>

subbers/templates/offline.html
debido a la falta de quorum se cierra....<br>

subbers/templates/pagination/pagination.html
{% if is_paginated %}
{% load i18n %}
    <ul class="pagination">
    {% if page_obj.has_Anterior %}
        <li><a href="?page={{ page_obj.Anterior_page_number }}{{ getvars }}{{ hashtag }}" class="prev">&lsaquo;&lsaquo; {% trans "Anterior" %}</a></li>
    {% else %}
        <li class="disabled prev"><a href="#">&lsaquo;&lsaquo; {% trans "Anterior" %}</a></li>
    {% endif %}
    {% for page in pages %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <li class="current page active"><a href="#">{{ page }}</a></li>
            {% else %}
                <li><a href="?page={{ page }}{{ getvars }}{{ hashtag }}" class="page">{{ page }}</a></li>
            {% endifequal %}
        {% else %}
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}{{ getvars }}{{ hashtag }}" class="Siguiente">{% trans "Siguiente" %} &rsaquo;&rsaquo;</a></li>
    {% else %}
        <li class="disabled next"><a href="#">{% trans "Siguiente" %} &rsaquo;&rsaquo;</a></li>
    {% endif %}
    </ul>
{% endif %}

subbers/templates/search/search.html
{% extends 'base.html' %}

{% block content %}

<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

    <h2>Buscar</h2>

    <form method="get" action=".">
        <table>
            {{ form.as_table }}
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Search">
                </td>
            </tr>
        </table>

        {% if query %}
            <h3>Resultados</h3>

           <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Fansub</th>
                  <th>Nombre</th>
                  <th>Cap</th>
                  <th>Cal</th>
                  <th>CRC</th>
                  <th>Descarga</th>
                  <th>Publicado</th>
                </tr>
              </thead>
              <tbody>
                {%for i in page.object_list %}
                <tr data-toggle="tooltip" data-placement="top" title="{{i.title}}">
                  <td>{{i.object.id}}</td>
                  {% if i.object.data %}
                  <td>{{i.object.fansub.name}}</td>
                  <td>{{i.object.data.name}}</td>
                  <td>{{i.object.data.chapter|default:""}}</td>
                  <td>{{i.object.data.quality|default:""}}</td>
                  <td>{{i.object.data.crc|default:""}}</td>
                  {% else %}
                    <td>{{i.object.fansub.name}}</td>
                    <td colspan="4">{{i.object.title}}</td>
                  {% endif %}
                  <td> <a href="{{i.object.link}}">Torrent</a></td>
                  <td> hace {{i.object.published_at|timesince}}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>

            
            {% comment %}
            {% for result in page.object_list %}
                <p>
                    <a href="{{ result.object.link }}">{{ result.object.title }}</a>
                </p>
            {% empty %}
                <p>No results found.</p>
            {% endfor %}
            {% endcomment %}
            {% if page.has_previous or page.has_next %}
                <div>
                    {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous{% if page.has_previous %}</a>{% endif %}
                    |
                    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next &raquo;{% if page.has_next %}</a>{% endif %}
                </div>
            {% endif %}
        {% else %}
        <h1>No encontrado</h1>
        {% endif %}
    </form>
</div>
{% endblock %}

subbers/templates/subbers/entry_list.html
{% extends "base.html" %}
 {% load pagination_tags %}

 {% block js %}

 {% endblock %}

{% block content %}
{% autopaginate object_list %}

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          {% if fansub %}
          <p>

          <div class="row center-block">
      <img src="{{fansub.logo|default:"http://s1.zerochan.net/Hoshizora.e.Kakaru.Hashi.600.146050.jpg"}}" /></br>

      </div>
      <h2>
        <a href="{{fansub.website}}">{{fansub.website}}</a> <small>
        
          {{fansub.irc|default:""}}
        </small>
        </h2>
        </br>
        <a href="http://www.nyaa.se/?page=separate&user={{fansub.nyaa_id}}">Perfil en nyaa</a>
          </p>
          {% endif %}

          <div class="table-responsive">
           {% paginate %}
              {% include "subbers/table/_table.html"%} 
           {% paginate %}
          </div>
        </div>
{% endblock %}

subbers/templates/subbers/table/_table.html
           <table class="table table-striped table-condensed">
              <thead>
                <tr>
                  <th colspan="2">Fansub</th>
                  <th>nombre</th>
                  <th>cap</th>
                  <th>cal</th>
                  <th>crc</th>
                  <th>Link</th>
                  <th>Publicada hace</th>
                </tr>
              </thead>
              <tbody>
                {%for i in object_list %}
                <tr data-toggle="tooltip" data-placement="top" title="{{i.title}}">
                  <td>{{i.fansub.name}}</td>
                  <td><small class="moresmall"> <a href="{{i.info}}">info</a></small></td>
                  {% if i.data %}
                  <td>{{i.data.name}}</td>
                  <td>{{i.data.chapter|default:""}}</td>
                  <td>{{i.data.quality|default:""}}</td>
                  <td>{{i.data.crc|default:""}}</td>
                  {% else %}
                    <td colspan="4">{{i.title}}</td>
                  {% endif %}
                  <td>
                    <a href="{{i.link}}">Torrent</a>
                    {% if i.magnet %}
                    <a href="{{i.magnet|safe}}"><img width=10 src="{{MEDIA_URL}}images/mag.png"></a>
                    {% endif %}
                  </td>
                  <td> {{i.published_at|timesince}}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>